### PR TITLE
Expose `on_error` in to_snowflake

### PR DESCRIPTION
**Pull request by nick-amplify**
Hey Dask team, 

Our team needed to use the `on_error` arg of `write_pandas` for our app, so I added it in here. 

Lmk what steps I can/should follow to merge this into the official package!

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @nick-amplify. Adding support for this seems reasonable to me. However, instead of making `on_error=` a top-level kwarg, I think I'd rather add a `write_pandas_kwargs=` argument (similar to the existing `connection_kwargs=` parameter) that we can use to forward keywords to the `write_pandas(...)` call we make. So something like

```python
to_snowflake(df, ..., write_pandas_kwargs={"on_error": "SKIP_FILE"})
```

**Comment by nick-amplify** [comment]
@jrbourbeau hey James! been awhile... but I got back around to this! changed to `write_pandas_kwargs` and the tests are passing!

**Comment by jrbourbeau** [comment]
I tried to merge `main` (where some test failures have been fixed) and push to this branch, but that somehow closed this PR...

Sorry about that @nick-amplify. I opened up https://github.com/coiled/dask-snowflake/pull/57 which has the same commits. Hope that's okay

**Comment by nick-amplify** [comment]
> I tried to merge `main` (where some test failures have been fixed) and push to this branch, but that somehow closed this PR...
> 
> Sorry about that @nick-amplify. I opened up #57 which has the same commits. Hope that's okay

Yeah that's cool with me!

**Pull request closed without merging**
