### PR TITLE
Remove `SerializebleLock` in `to_snowflake`

### LINKED ISSUE #29: Questioning lock necessity in `write_snowflake`
Hi there,

Looking at the implementation, there is a `SerializableLock` in the `write_snowflake` function. Looking at the linked issue above the `SerializableLock`, it seems to be related to the SQL `PARALLEL = <n_workers>` query option. However, looking at the documentation of `write_pandas` and in particular the `parallel=1`, that option seems to set `PARALLEL = 1`. 

Therefore, does the lock buy us anything?

The lock has always been a part of this codebase, so I cannot point to a PR where it was added for a given specific reason. I am opening this issue to shed some light on this lock which might be unnecessary.

### PR DESCRIPTION
**Pull request by phobson**
Fixes #29 

Just testing things out for now

### CODE REVIEW

**Comment by phobson** [comment]
With the larger dataframe, the partition sizes when we read back from snowflake are coming back a bit erratically sized. This is without any changes to core.py

Locally, I get:
```
     result  expected
0   1677752  2097152
1   1787420  2097152
2   2288648  2097152
3   4578130  2097152
4   1904888  2097152
5   1788330  2097152
6   2288154  2097152
7   4580002  2097152
8   1904888  2097152
9   1344588  2097152
10  1787238  2097152
11  2287062  2097152
12  4576284  2097152
13  1686098  2097152
14   896452  2097152
15  1788174  2097152
16  2289194  2097152
17  1763526  2097152
18  1787966  2097152
19  2289116  2097152
20  4579820  2097152
21  2470206  2097152
22  1678038  2097152
23  1787134  2097152
24  2286802  2097152
25  2335578  2097152
26  1677908  2097152
27  1786822  2097152
28  2289766  2097152
29  3456256  2097152
30  1678116  2097152
31  1788694  2097152
32  2288466  2097152
33  4579456  2097152
34  2021108  2097152

**Comment by phobson** [comment]
Push a commit to remove the SerializableLock. The difference in test durations is substantial:


Without 399da1465a208d5ec4459059461ecd4ed0aa104e (status quo):
```
============================================= slowest 10 durations =============================================
708.74s call     dask_snowflake/tests/test_core.py::test_result_batching_nparitions_and_equality[twelve months]
664.69s call     dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[twelve months]
76.58s call     dask_snowflake/tests/test_core.py::test_result_batching_nparitions_and_equality[one month]
63.95s call     dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[one month]
9.74s call     dask_snowflake/tests/test_core.py::test_application_id_config
8.94s call     dask_snowflake/tests/test_core.py::test_application_id_default
8.27s call     dask_snowflake/tests/test_core.py::test_application_id_explicit
7.54s call     dask_snowflake/tests/test_core.py::test_write_read_roundtrip
7.01s call     dask_snowflake/tests/test_core.py::test_execute_params
6.94s call     dask_snowflake/tests/test_core.py::test_read_empty_result
=========================================== short test summary info ============================================
XFAIL dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[twelve months] - inconsistent partition sizing
=========================== 11 passed, 1 xfailed, 46 warnings in 1601.74s (0:26:41) ============================
```

With 399da1465a208d5ec4459059461ecd4ed0aa104e (this PR):
```
============================================= slowest 10 durations =============================================
175.20s call     dask_snowflake/tests/test_core.py::test_result_batching_nparitions_and_equality[twelve months]
115.40s call     dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[twelve months]
27.99s call     dask_snowflake/tests/test_core.py::test_result_batching_nparitions_and_equality[one month]
26.80s call     dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[one month]
7.11s call     dask_snowflake/tests/test_core.py::test_application_id_explicit
7.11s call     dask_snowflake/tests/test_core.py::test_write_read_roundtrip
7.11s call     dask_snowflake/tests/test_core.py::test_application_id_config_on_cluster
6.97s call     dask_snowflake/tests/test_core.py::test_execute_params
6.93s call     dask_snowflake/tests/test_core.py::test_arrow_options
6.71s call     dask_snowflake/tests/test_core.py::test_application_id_default
=========================================== short test summary info ============================================
XFAIL dask_snowflake/tests/test_core.py::test_result_batching_partition_sizes[twelve months] - inconsistent partition sizing
============================ 11 passed, 1 xfailed, 46 warnings in 425.89s (0:07:05) ============================
```

**Comment by phobson** [comment]
SImilar performance boost in CI:

With Lock: https://github.com/coiled/dask-snowflake/actions/runs/3535816356/jobs/5934242005#step:5:70
Without Lock: https://github.com/coiled/dask-snowflake/actions/runs/3536012799/jobs/5934652801#step:5:70

**Comment by dchudz** [comment]
@jrbourbeau is this something we should revisit?

**Comment by fjetter** [comment]
@jrbourbeau are you still on this?

**Review by jrbourbeau — APPROVED** [review]

**Comment by phobson** [comment]
Heyyy look that it. Finally merged! 🎉

**Comment by mrocklin** [comment]
You just gotta plant a lotta seeds 🙂

**Pull request merged**
