### PR TITLE
Converting from HLG to from_map

### PR DESCRIPTION
**Pull request by alex-rakowski**
@phofl @fjetter 

Replacing HLG with `dd.from_map` to enable dask_expr functionality. Reverts to existing method if dask version doesn't support `from_map`.

### CODE REVIEW

**Comment by phofl** [comment]
I think I would prefer just requiring a minimum version that definitely supports from_map

**Comment by ntabris** [comment]
> I think I would prefer just requiring a minimum version that definitely supports from_map

What would this minimum version be?

**Comment by alex-rakowski** [comment]
@phofl  @jrbourbeau  I think this is good to go, the failing tests c.f. deprecation of 3.7 and 3.8

**Comment by phofl** [comment]
Ah sorry, just merge main and the failures will go away

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx

**Pull request merged**
