### PR TITLE
Use `arrow_options` with computing `meta`

### PR DESCRIPTION
**Pull request by jrbourbeau**
On a call with @ncclementi today I noticed we're not using `arrow_options` when computing `meta` but we are when computing partitions. This could lead to `meta` not being correct. This PR makes sure we use `arrow_options` accordingly.

### CODE REVIEW

**Comment by ncclementi** [comment]
LGTM, @jrbourbeau can you fix the linting issue?

**Review by ncclementi — APPROVED** [review]

**Comment by jrbourbeau** [comment]
Thanks @ncclementi. That unrelated linting failure should be fixed by https://github.com/coiled/dask-snowflake/pull/32

Also, let me see if I can add a quick test for the changes here...

**Comment by jrbourbeau** [comment]
I wasn't able to get my local snowflake setup working...let's see if this test passes in CI 🤞

**Comment by jrbourbeau** [comment]
Okay, this is good to go -- thanks @ncclementi

**Comment by mrocklin** [comment]
It's nice to see the rapid merging of small but important changes like this :)

**Pull request merged**
